### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Evanion** [feathersjs/feathers-authentication-openid#1]
I'm not sure how you implement semver in feathers, so I didn't change the version tag in the package.json. 
should we roll it back to 0.1.0 until the package is published as 1.0.0, or does it follow the main feathers.js version?

**Comment by daffl** [comment]
Each package has its own Semantic Versioning. I would start with 0.1.0, progress through 0.x and only go 1.0 once the API is finalized and ideally maybe tested in production.
